### ISSUE TITLE
Sprint 3 Review

### ISSUE THREAD

**Issue by MissHockey15** [Epsilon-JIJ/Concert-Concierge#16]
Created layout sketches and began prototype.

**Comment by MissHockey15** [comment]
During sprint week I created sketches for a possible mobile and desktop website look. We had created a flow and decided what pages we would include before hand so that the sketching process was easier. The flow was already set so Iza and I came up with two possible layout looks.

**Comment by IFVG45** [comment]
For week 3 sprint, I was able to create sketches to use for the wireframes layout the flow that we created helped me a lot in order to build it up. That way we're able to start building up that final concept once we all agree on a final sketch. I feel researching and creating more sketches could have gave us more options instead of just creating one or two.

**Comment by jsurtees** [comment]
Desktop Prototype was completed. Mobile prototype was not completed.

**Comment by jsurtees** [comment]
@thomasjbradley
