### ISSUE TITLE
Coded app rubric

### ISSUE THREAD

**Issue by IFVG45** [Epsilon-JIJ/Concert-Concierge#9]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Quality of content** | not real content | some content, not descriptive or thorough | good content, fairly descriptive | great content, lots of detail, very descriptive |
| **Responsiveness** | Not responsive | Somewhat responsive | responsive with awkwardness | great on all screen sizes |
| **Accessibility** | No considerations | Some alt attributes, nothing else | basics, alt attributes, roles | Accessibility well considered and tested |
| **Performance** | Mega slow | Slow | Could be faster | Super fast |
| **Code quality (semantics, cleanliness)** | Barely started | Poor semantics | Decent semantics | Perfect semantics |
| **Commit quality** | Did not Commit | Barely Committed | Good amount of commits | Tons of commits, well detailed |
| **Testing results** | Did not test | Somewhat tested, poor feedback | Good testing and feedback | Fully tested, solid feedback |

**Comment by MissHockey15** [comment]
Quality of Content — 2.5

Over all the quality of our content was good. We had written content on each of the cards that was specific to each band that we showcased. We also had some written content specific concert page to talk about the band and the concert itself. Although the content is good we could have made more pages for each of the bands so that we could add more written content. 

Responsiveness — 3

Our website works great on all sizes. It has the capability to look nice on a large screen and a small screen. On desktop the cards of the concerts site nicely in a grid of three and shrink down to a grid of one on a small screen. 

Accessibility — 1

In our code we included basic alt attributes for our images. We also did not include many aria descriptions.

Performance — 2

Our website has a medium speed performance which makes it pretty fast on most devices however it could be a lot faster if we optimized the images to be smaller then what we had previously done.

Code Quality — 2.5

The organization of our HTML is great. It is indented in all the right places however there are some organizational issues with our css. There is a lot of empty lines dividing sections of code that could have been removed and also remove the commented code.

Commit Quality — 3

Commits were made often within new branches. They were descriptive - that way when the other group members looked at the code before merging it they were able to fully understand what changes were made.

Testing Results — 3

We fully tested our website when we finished it. We each handed off the website to other people to test it out. With the feed back we got we were able to make the necessary changes to the padding, usability, etc. to accommodate the feedback.
